### ISSUE TITLE
bug: typo mistake in assessment coordinator module - "assesment coordinator" should be "assessment coordinator"

### ISSUE THREAD

**Issue by faizan-20** [OPJU-Developers-Community/opju-exam-portal-be#23]
## Issue desciption
There is a typo in ``assessmentCoordinator`` model. Change the name of the model from ``assesmentCoordinator`` to ```assessmentCoordinator```.

This is a breaking change that is why I am creating a separate issue. Fix this before resolving other issues related to assessmentCoordinator.

## Expected behavior
- Model name for Assessment Coordinator should be ``AssessmentCoordinator``
- Schema name should be ``assessment_coordinator``
- JOI validation variable should be ``validateAssessmentCoordinator ``

## Actual Behaviour
- Model name for Assessment Coordinator is ``AssesmentCordinator``
- Schema name is ``assesment_coordinator``
- JOI validation is ``validateAssesmentCoordinator ``

### Checklist

- [X] Before submitting a PR, execute any associated test cases to help diagnose issues more effectively.

@subrat611 @Tanusingh02 @PalakAgrawal020 @svandu @aniimessh

**Comment by subrat611** [comment]
Read the guidelines before creating an issue.

Wrong title format

**Comment by faizan-20** [comment]
@subrat611 check if the issue description meets the need.

**Comment by subrat611** [comment]
@faizan-20 plz check the issue title, not the body or description.

"title" -> `[Refactor]: Rename model assesment-coordinator to assessment-coordinator`.

- Wrong format
- spelling mistake (optional)

It should be as per the guideline 

![image](https://github.com/OPJU-Developers-Community/opju-exam-portal-be/assets/77252075/28542f87-6b79-49fe-aee4-f40965f5fa34)

Also, check other issues that were already created after the guideline was added.

![image](https://github.com/OPJU-Developers-Community/opju-exam-portal-be/assets/77252075/30290979-d7c2-48cd-ab78-d3db86932c36)

Do follow a small case for your title if the key name is same as in case of all "All" which can be acceptable for better readability and understanding.

`TAKE YOUR TIME TO UNDERSTAND THE FLOW`

`NOTE: PLS FOLLOW ALREADY CREATED ISSUE, TO KNOW THE FORMAT`

**Comment by subrat611** [comment]
@faizan-20 This is not a `refactor` issue this is a `bug`.

That you mention here `This is a breaking change`. 

If the system fails to do something then it must be a `bug`, which produced unaccepted behavior in the code base.

**Comment by faizan-20** [comment]
@subrat611 

you should change the issue template to reflect the new changes to avoid confusion in title.

![Screenshot from 2023-12-02 23-34-19](https://github.com/OPJU-Developers-Community/opju-exam-portal-be/assets/69417253/bbbb0bad-5b6f-425b-aaf1-dca8b3f8af16)
