### ISSUE TITLE
feat: implement a utility function that separates the full name as first name and last name

### ISSUE THREAD

**Issue by svandu** [OPJU-Developers-Community/opju-exam-portal-be#29]
### Feature description

I want to create a utility function that separates the full name as first name and last name.

**For example**
A function called `separateFullName` takes a `full name` as an argument and returns the `first name` and `last name`.

@subrat611 Please assign this issue to me

### Checklist

- [X] Before submitting a PR, execute any associated test cases to help diagnose issues more effectively.

**Comment by subrat611** [comment]
@svandu how much time would you take to complete it?

**Comment by svandu** [comment]
@subrat611  
It will take 1 day 2hr to complete.

**Comment by subrat611** [comment]
Ok then assign it to you.

@svandu Happy coding 🌟

**Comment by svandu** [comment]
Hey, @subrat611 will you tell me where should I create the file `seperateFullName` to implement this function?

**Comment by subrat611** [comment]
You can create the file within the folder named as `utils`.

Change the file name from `separateFullName` to `splitFullName`

@svandu

**Comment by svandu** [comment]
Ok I'll do it accordingly 
@subrat611

**Comment by subrat611** [comment]
@svandu Did you implement this feature?

Its more than 1 day 4hr.

**Comment by subrat611** [comment]
@svandu 

Please update your branch with the main branch.

Then run `npm run test ./utils/__tests__` in you terminal.
